#!/usr/bin/env python3
"""Sync Kim Wannachar's Medium posts into index.html's #articles section.

Fetches the Medium RSS feed, then rewrites the block between the
MEDIUM-ARTICLES:START/END comments in index.html with one <article> card
per post (newest first, as Medium returns them).

Curated Thai/English copy for a post lives in data/medium-overrides.json,
keyed by the post's URL slug. Posts without an override entry get an
auto-generated excerpt (same text in both languages) and a tag guessed
from the post's Medium categories.
"""
import html
import json
import re
import sys
import urllib.request
from email.utils import parsedate_to_datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INDEX = ROOT / "index.html"
OVERRIDES_PATH = ROOT / "data" / "medium-overrides.json"

FEED_URL = "https://medium.com/feed/@kimwannachar."
START_MARKER = "<!-- MEDIUM-ARTICLES:START -->"
END_MARKER = "<!-- MEDIUM-ARTICLES:END -->"

TH_MONTHS = ["ม.ค.", "ก.พ.", "มี.ค.", "เม.ย.", "พ.ค.", "มิ.ย.",
             "ก.ค.", "ส.ค.", "ก.ย.", "ต.ค.", "พ.ย.", "ธ.ค."]
EN_MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
             "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]

SYS_KEYWORDS = ["system-design", "backend", "engineering", "architecture",
                "software", "frugal-ai", "devops", "database", "distributed", "ai"]
MIND_KEYWORDS = ["psycholog", "leadership", "personality", "self-improvement",
                  "maslow", "team-building", "johari", "motivation",
                  "behavior", "belief", "mind"]


def fetch_feed(url: str) -> str:
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req, timeout=20) as resp:
        return resp.read().decode("utf-8")


def parse_items(xml_text: str):
    items = []
    for raw in xml_text.split("<item>")[1:]:
        body = raw.split("</item>")[0]

        def grab(pattern, default=""):
            m = re.search(pattern, body, re.S)
            return m.group(1) if m else default

        title = html.unescape(grab(r"<title><!\[CDATA\[(.*?)\]\]></title>"))
        link = grab(r"<link>(.*?)</link>").split("?")[0].strip()
        pub_raw = grab(r"<pubDate>(.*?)</pubDate>")
        categories = re.findall(r"<category><!\[CDATA\[(.*?)\]\]></category>", body)
        content = grab(r"<content:encoded><!\[CDATA\[(.*?)\]\]></content:encoded>")
        if link:
            items.append({
                "title": title,
                "link": link,
                "pub_raw": pub_raw,
                "categories": categories,
                "content": content,
            })
    return items


def excerpt_from_content(content_html: str, limit: int = 140) -> str:
    # Drop <figure>...</figure> blocks (images/captions like "generated by
    # chatGPT, prompt by ...") so they don't bleed into the excerpt text.
    text = re.sub(r"<figure>.*?</figure>", " ", content_html, flags=re.S)
    text = re.sub(r"<[^>]+>", " ", text)
    text = html.unescape(text)
    text = re.sub(r"\s+", " ", text).strip()
    if len(text) > limit:
        text = text[:limit].rsplit(" ", 1)[0] + "…"
    return text


def classify(categories, title):
    hay = " ".join(categories + [title]).lower()
    if any(k in hay for k in MIND_KEYWORDS):
        return "mind", "จิตวิทยา · Leadership", "Mind · Leadership"
    if any(k in hay for k in SYS_KEYWORDS):
        return "sys", "System Design", "System Design"
    return "sys", "บทความ", "Article"


def format_date(pub_raw: str):
    dt = parsedate_to_datetime(pub_raw)
    return f"{TH_MONTHS[dt.month - 1]} {dt.year}", f"{EN_MONTHS[dt.month - 1]} {dt.year}"


def slug_of(link: str) -> str:
    return link.rstrip("/").rsplit("/", 1)[-1]


def render_article(item, override):
    th_date, en_date = format_date(item["pub_raw"])
    swatch, tag_th_default, tag_en_default = classify(item["categories"], item["title"])

    if override:
        title_th = override.get("title_th", item["title"])
        title_en = override.get("title_en", item["title"])
        desc_th = override.get("desc_th") or excerpt_from_content(item["content"])
        desc_en = override.get("desc_en") or desc_th
        tag_th = override.get("tag_th", tag_th_default)
        tag_en = override.get("tag_en", tag_en_default)
        swatch = override.get("swatch", swatch)
    else:
        title_th = title_en = item["title"]
        desc_th = desc_en = excerpt_from_content(item["content"])
        tag_th, tag_en = tag_th_default, tag_en_default

    esc = lambda s: html.escape(s, quote=False)

    if title_th == title_en:
        title_html = esc(title_th)
    else:
        title_html = (f'<span class="th">{esc(title_th)}</span>'
                       f'<span class="en">{esc(title_en)}</span>')

    return f'''    <article class="article">
      <div class="swatch sw-{swatch}" aria-hidden="true"></div>
      <div>
        <h3><a href="{html.escape(item['link'], quote=True)}" target="_blank" rel="noopener">{title_html}</a></h3>
        <p><span class="th">{esc(desc_th)}</span>
           <span class="en">{esc(desc_en)}</span></p>
        <span class="tag tag-{swatch}"><span class="th">{esc(tag_th)}</span><span class="en">{esc(tag_en)}</span></span>
      </div>
      <span class="meta"><span class="th">{th_date}</span><span class="en">{en_date}</span></span>
    </article>'''


def main():
    xml_text = fetch_feed(FEED_URL)
    items = parse_items(xml_text)
    if not items:
        print("No items found in feed; leaving index.html untouched.", file=sys.stderr)
        sys.exit(1)

    overrides = {}
    if OVERRIDES_PATH.exists():
        overrides = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))

    blocks = [render_article(item, overrides.get(slug_of(item["link"]))) for item in items]
    new_section = "\n\n".join(blocks)

    html_text = INDEX.read_text(encoding="utf-8")
    if START_MARKER not in html_text or END_MARKER not in html_text:
        print("Markers not found in index.html", file=sys.stderr)
        sys.exit(1)

    pattern = re.compile(re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER), re.S)
    replacement = f"{START_MARKER}\n{new_section}\n    {END_MARKER}"
    updated = pattern.sub(replacement, html_text)

    if updated != html_text:
        INDEX.write_text(updated, encoding="utf-8")
        print(f"Updated index.html with {len(items)} articles.")
    else:
        print("No changes.")


if __name__ == "__main__":
    main()
